/* ─── Dados iniciais do Gerador de Contratos ────────────────── */

import type { Clausula, ModeloContrato, Regra } from "./types";

const agora = new Date().toISOString();

export const SEED_CLAUSULAS: Clausula[] = [
  {
    id: "cl-objeto-servicos",
    titulo: "Do Objeto",
    categoria: "Objeto",
    descricao: "Define o objeto da prestação de serviços",
    texto: "O presente contrato tem por objeto a prestação, pelo CONTRATADO ao CONTRATANTE, dos seguintes serviços: {{DESCRICAO_SERVICOS}}, que serão executados com zelo, diligência e observância das normas técnicas aplicáveis.",
    tags: ["objeto", "serviços"],
    versao: 1, autor: "Sistema", criadaEm: agora, status: "ativa", favorita: true,
  },
  {
    id: "cl-valor-pagamento",
    titulo: "Do Valor e Forma de Pagamento",
    categoria: "Financeiro",
    descricao: "Valor do contrato e condições de pagamento",
    texto: "Pelos serviços objeto deste contrato, o CONTRATANTE pagará ao CONTRATADO o valor total de {{VALOR}} ({{VALOR_EXTENSO}}), a ser pago da seguinte forma: {{FORMA_PAGAMENTO}}.",
    tags: ["valor", "pagamento"],
    versao: 1, autor: "Sistema", criadaEm: agora, status: "ativa", favorita: true,
  },
  {
    id: "cl-prazo",
    titulo: "Do Prazo",
    categoria: "Prazo",
    descricao: "Prazo de vigência do contrato",
    texto: "O presente contrato vigorará pelo prazo de {{PRAZO}}, com início em {{DATA_INICIO}} e término em {{DATA_FIM}}, podendo ser prorrogado mediante termo aditivo assinado pelas partes.",
    tags: ["prazo", "vigência"],
    versao: 1, autor: "Sistema", criadaEm: agora, status: "ativa", favorita: false,
  },
  {
    id: "cl-obrigacoes-contratado",
    titulo: "Das Obrigações do Contratado",
    categoria: "Obrigações",
    descricao: "Deveres do contratado",
    texto: "São obrigações do CONTRATADO:\na) executar os serviços contratados com qualidade e dentro dos prazos acordados;\nb) manter sigilo sobre todas as informações do CONTRATANTE a que tiver acesso;\nc) arcar com todos os encargos trabalhistas, previdenciários e fiscais decorrentes da execução deste contrato;\nd) comunicar imediatamente ao CONTRATANTE qualquer fato que possa comprometer a execução dos serviços.",
    tags: ["obrigações"],
    versao: 1, autor: "Sistema", criadaEm: agora, status: "ativa", favorita: false,
  },
  {
    id: "cl-obrigacoes-contratante",
    titulo: "Das Obrigações do Contratante",
    categoria: "Obrigações",
    descricao: "Deveres do contratante",
    texto: "São obrigações do CONTRATANTE:\na) fornecer ao CONTRATADO todas as informações e documentos necessários à execução dos serviços;\nb) efetuar os pagamentos nas datas e condições pactuadas;\nc) comunicar ao CONTRATADO, por escrito, qualquer irregularidade verificada na execução dos serviços.",
    tags: ["obrigações"],
    versao: 1, autor: "Sistema", criadaEm: agora, status: "ativa", favorita: false,
  },
  {
    id: "cl-multa-inadimplencia",
    titulo: "Da Inadimplência e Multa",
    categoria: "Penalidades",
    descricao: "Multa e juros por atraso de pagamento",
    texto: "O atraso no pagamento de qualquer parcela implicará multa de {{PERCENTUAL_MULTA}} sobre o valor devido, acrescida de juros de mora de 1% (um por cento) ao mês e correção monetária pelo índice IPCA, sem prejuízo da possibilidade de rescisão contratual após 30 (trinta) dias de inadimplência.",
    tags: ["multa", "inadimplência", "juros"],
    versao: 1, autor: "Sistema", criadaEm: agora, status: "ativa", favorita: true,
  },
  {
    id: "cl-rescisao",
    titulo: "Da Rescisão",
    categoria: "Rescisão",
    descricao: "Condições de rescisão contratual",
    texto: "O presente contrato poderá ser rescindido por qualquer das partes, mediante notificação prévia e por escrito com antecedência mínima de 30 (trinta) dias, sem prejuízo do cumprimento das obrigações pendentes até a data da efetiva rescisão.",
    tags: ["rescisão"],
    versao: 1, autor: "Sistema", criadaEm: agora, status: "ativa", favorita: false,
  },
  {
    id: "cl-confidencialidade",
    titulo: "Da Confidencialidade",
    categoria: "Confidencialidade",
    descricao: "Sigilo sobre informações trocadas entre as partes",
    texto: "As partes obrigam-se a manter em absoluto sigilo todas as informações confidenciais, técnicas, comerciais ou estratégicas a que tiverem acesso em razão deste contrato, obrigação que permanecerá vigente pelo prazo de 5 (cinco) anos após o término da relação contratual, sob pena de responder por perdas e danos.",
    tags: ["confidencialidade", "sigilo", "NDA"],
    versao: 1, autor: "Sistema", criadaEm: agora, status: "ativa", favorita: true,
  },
  {
    id: "cl-lgpd",
    titulo: "Da Proteção de Dados (LGPD)",
    categoria: "LGPD",
    descricao: "Conformidade com a Lei Geral de Proteção de Dados",
    texto: "As partes comprometem-se a tratar os dados pessoais a que tiverem acesso em conformidade com a Lei nº 13.709/2018 (Lei Geral de Proteção de Dados — LGPD), utilizando-os exclusivamente para as finalidades deste contrato, adotando medidas técnicas e administrativas de segurança e comunicando imediatamente à outra parte qualquer incidente de segurança envolvendo dados pessoais.",
    tags: ["LGPD", "dados", "privacidade"],
    versao: 1, autor: "Sistema", criadaEm: agora, status: "ativa", favorita: true,
  },
  {
    id: "cl-garantia",
    titulo: "Da Garantia",
    categoria: "Garantia",
    descricao: "Garantia sobre serviços/bens de maior valor",
    texto: "O CONTRATADO garante a qualidade dos serviços/bens objeto deste contrato pelo prazo de {{PRAZO_GARANTIA}}, comprometendo-se a corrigir, sem custo adicional, quaisquer vícios ou defeitos constatados nesse período, desde que não decorrentes de mau uso.",
    tags: ["garantia"],
    versao: 1, autor: "Sistema", criadaEm: agora, status: "ativa", favorita: false,
  },
  {
    id: "cl-nao-concorrencia",
    titulo: "Da Não Concorrência",
    categoria: "Restrições",
    descricao: "Vedação à concorrência direta",
    texto: "O CONTRATADO obriga-se, durante a vigência deste contrato e pelo período de 12 (doze) meses após seu término, a não exercer, direta ou indiretamente, atividade concorrente à do CONTRATANTE na mesma área de atuação e limite territorial de {{CIDADE_FORO}}, sob pena de multa equivalente a 3 (três) vezes o valor mensal deste contrato.",
    tags: ["não concorrência"],
    versao: 1, autor: "Sistema", criadaEm: agora, status: "ativa", favorita: false,
  },
  {
    id: "cl-cancelamento-curso",
    titulo: "Da Política de Cancelamento",
    categoria: "Cancelamento",
    descricao: "Política de cancelamento para cursos",
    texto: "O ALUNO/CONTRATANTE poderá cancelar a matrícula em até 7 (sete) dias corridos após a contratação, com devolução integral dos valores pagos (art. 49 do CDC). Após esse prazo, o cancelamento implicará retenção proporcional dos valores referentes ao período já disponibilizado, acrescida de multa compensatória de 10% (dez por cento) sobre o saldo remanescente.",
    tags: ["cancelamento", "curso", "CDC"],
    versao: 1, autor: "Sistema", criadaEm: agora, status: "ativa", favorita: false,
  },
  {
    id: "cl-responsavel-legal",
    titulo: "Do Responsável Legal",
    categoria: "Capacidade",
    descricao: "Cláusula para contratos envolvendo menores",
    texto: "Sendo o beneficiário dos serviços menor de 18 (dezoito) anos ou civilmente incapaz, o presente contrato é firmado por seu RESPONSÁVEL LEGAL, que assume integralmente todas as obrigações aqui previstas, inclusive as de natureza financeira.",
    tags: ["menor", "responsável legal"],
    versao: 1, autor: "Sistema", criadaEm: agora, status: "ativa", favorita: false,
  },
  {
    id: "cl-foro",
    titulo: "Do Foro",
    categoria: "Foro",
    descricao: "Eleição de foro para dirimir conflitos",
    texto: "Fica eleito o foro da comarca de {{CIDADE_FORO}}, com renúncia expressa a qualquer outro, por mais privilegiado que seja, para dirimir quaisquer controvérsias oriundas do presente contrato.",
    tags: ["foro"],
    versao: 1, autor: "Sistema", criadaEm: agora, status: "ativa", favorita: true,
  },
  {
    id: "cl-locacao-objeto",
    titulo: "Do Objeto da Locação",
    categoria: "Objeto",
    descricao: "Objeto para contrato de locação",
    texto: "O LOCADOR dá em locação ao LOCATÁRIO o imóvel situado em {{ENDERECO_IMOVEL}}, destinado exclusivamente a {{FINALIDADE_LOCACAO}}, nos termos da Lei nº 8.245/91.",
    tags: ["locação", "imóvel"],
    versao: 1, autor: "Sistema", criadaEm: agora, status: "ativa", favorita: false,
  },
  {
    id: "cl-compra-venda-objeto",
    titulo: "Do Objeto da Compra e Venda",
    categoria: "Objeto",
    descricao: "Objeto para contrato de compra e venda",
    texto: "O VENDEDOR vende ao COMPRADOR, que aceita e compra, o seguinte bem: {{DESCRICAO_BEM}}, livre e desembaraçado de quaisquer ônus, dívidas ou gravames.",
    tags: ["compra e venda"],
    versao: 1, autor: "Sistema", criadaEm: agora, status: "ativa", favorita: false,
  },
];

const CAMPOS_BASE = [
  { id: "c-valor", label: "Valor total (R$)", tipo: "valor" as const, variavel: "VALOR", obrigatorio: true },
  { id: "c-forma-pgto", label: "Forma de pagamento", tipo: "select" as const, variavel: "FORMA_PAGAMENTO", obrigatorio: true, opcoes: ["À vista", "Parcelado", "Mensal", "Entrada + parcelas"] },
  { id: "c-prazo", label: "Prazo de vigência", tipo: "texto" as const, variavel: "PRAZO", obrigatorio: true, placeholder: "ex: 12 (doze) meses" },
  { id: "c-data-inicio", label: "Data de início", tipo: "data" as const, variavel: "DATA_INICIO", obrigatorio: true },
  { id: "c-data-fim", label: "Data de término", tipo: "data" as const, variavel: "DATA_FIM", obrigatorio: false },
  { id: "c-foro", label: "Cidade do foro", tipo: "texto" as const, variavel: "CIDADE_FORO", obrigatorio: true, placeholder: "ex: Uberaba/MG" },
];

export const SEED_MODELOS: ModeloContrato[] = [
  {
    id: "mod-prestacao-servicos",
    nome: "Prestação de Serviços",
    categoria: "Empresarial",
    descricao: "Contrato de prestação de serviços entre contratante e contratado",
    icone: "🤝", cor: "#34d399", status: "ativo", versao: 1,
    tituloDocumento: "Contrato de Prestação de Serviços",
    preambulo: "As partes acima qualificadas resolvem celebrar o presente CONTRATO DE PRESTAÇÃO DE SERVIÇOS, que se regerá pelas cláusulas e condições seguintes.",
    fechamento: "E, por estarem justas e contratadas, as partes assinam o presente instrumento em 2 (duas) vias de igual teor e forma, na presença das testemunhas abaixo.",
    campos: [
      { id: "c-desc-serv", label: "Descrição dos serviços", tipo: "textarea", variavel: "DESCRICAO_SERVICOS", obrigatorio: true },
      ...CAMPOS_BASE,
    ],
    clausulasObrigatorias: ["cl-objeto-servicos", "cl-valor-pagamento", "cl-prazo", "cl-obrigacoes-contratado", "cl-obrigacoes-contratante", "cl-rescisao", "cl-foro"],
    clausulasOpcionais: ["cl-confidencialidade", "cl-lgpd", "cl-multa-inadimplencia", "cl-garantia", "cl-nao-concorrencia"],
    minAssinantes: 2,
  },
  {
    id: "mod-consultoria",
    nome: "Consultoria",
    categoria: "Empresarial",
    descricao: "Contrato de consultoria empresarial ou técnica",
    icone: "💼", cor: "#93c5fd", status: "ativo", versao: 1,
    tituloDocumento: "Contrato de Consultoria",
    preambulo: "As partes acima qualificadas resolvem celebrar o presente CONTRATO DE CONSULTORIA, que se regerá pelas cláusulas e condições seguintes.",
    fechamento: "E, por estarem justas e contratadas, as partes assinam o presente instrumento em 2 (duas) vias de igual teor e forma.",
    campos: [
      { id: "c-desc-serv", label: "Escopo da consultoria", tipo: "textarea", variavel: "DESCRICAO_SERVICOS", obrigatorio: true },
      ...CAMPOS_BASE,
    ],
    clausulasObrigatorias: ["cl-objeto-servicos", "cl-valor-pagamento", "cl-prazo", "cl-confidencialidade", "cl-rescisao", "cl-foro"],
    clausulasOpcionais: ["cl-lgpd", "cl-multa-inadimplencia", "cl-nao-concorrencia"],
    minAssinantes: 2,
  },
  {
    id: "mod-locacao",
    nome: "Locação",
    categoria: "Imobiliário",
    descricao: "Contrato de locação de imóvel residencial ou comercial",
    icone: "🏠", cor: "#fbbf24", status: "ativo", versao: 1,
    tituloDocumento: "Contrato de Locação de Imóvel",
    preambulo: "As partes acima qualificadas, doravante denominadas LOCADOR e LOCATÁRIO, celebram o presente CONTRATO DE LOCAÇÃO, regido pela Lei nº 8.245/91 e pelas cláusulas seguintes.",
    fechamento: "E, por estarem justas e contratadas, firmam o presente em 2 (duas) vias de igual teor, na presença das testemunhas abaixo.",
    campos: [
      { id: "c-end-imovel", label: "Endereço do imóvel", tipo: "texto", variavel: "ENDERECO_IMOVEL", obrigatorio: true },
      { id: "c-finalidade", label: "Finalidade", tipo: "select", variavel: "FINALIDADE_LOCACAO", obrigatorio: true, opcoes: ["fins residenciais", "fins comerciais"] },
      ...CAMPOS_BASE,
    ],
    clausulasObrigatorias: ["cl-locacao-objeto", "cl-valor-pagamento", "cl-prazo", "cl-multa-inadimplencia", "cl-rescisao", "cl-foro"],
    clausulasOpcionais: ["cl-lgpd", "cl-garantia"],
    minAssinantes: 2,
  },
  {
    id: "mod-compra-venda",
    nome: "Compra e Venda",
    categoria: "Civil",
    descricao: "Contrato de compra e venda de bens móveis ou imóveis",
    icone: "🛒", cor: "#f87171", status: "ativo", versao: 1,
    tituloDocumento: "Contrato de Compra e Venda",
    preambulo: "As partes acima qualificadas celebram o presente CONTRATO DE COMPRA E VENDA, mediante as cláusulas e condições seguintes.",
    fechamento: "E, por estarem justas e contratadas, firmam o presente em 2 (duas) vias de igual teor e forma.",
    campos: [
      { id: "c-desc-bem", label: "Descrição do bem", tipo: "textarea", variavel: "DESCRICAO_BEM", obrigatorio: true },
      ...CAMPOS_BASE,
    ],
    clausulasObrigatorias: ["cl-compra-venda-objeto", "cl-valor-pagamento", "cl-foro"],
    clausulasOpcionais: ["cl-garantia", "cl-multa-inadimplencia", "cl-lgpd"],
    minAssinantes: 2,
  },
  {
    id: "mod-curso",
    nome: "Curso / Treinamento",
    categoria: "Educacional",
    descricao: "Contrato de prestação de serviços educacionais",
    icone: "🎓", cor: "#c4b5fd", status: "ativo", versao: 1,
    tituloDocumento: "Contrato de Prestação de Serviços Educacionais",
    preambulo: "As partes acima qualificadas celebram o presente CONTRATO DE PRESTAÇÃO DE SERVIÇOS EDUCACIONAIS, mediante as cláusulas seguintes.",
    fechamento: "E, por estarem justas e contratadas, firmam o presente em 2 (duas) vias de igual teor.",
    campos: [
      { id: "c-desc-serv", label: "Curso / conteúdo programático", tipo: "textarea", variavel: "DESCRICAO_SERVICOS", obrigatorio: true },
      { id: "c-menor", label: "Aluno é menor de idade?", tipo: "select", variavel: "ALUNO_MENOR", obrigatorio: true, opcoes: ["Não", "Sim"] },
      ...CAMPOS_BASE,
    ],
    clausulasObrigatorias: ["cl-objeto-servicos", "cl-valor-pagamento", "cl-prazo", "cl-cancelamento-curso", "cl-foro"],
    clausulasOpcionais: ["cl-lgpd", "cl-multa-inadimplencia", "cl-responsavel-legal"],
    minAssinantes: 2,
  },
  {
    id: "mod-nda",
    nome: "Confidencialidade (NDA)",
    categoria: "Empresarial",
    descricao: "Acordo de confidencialidade e não divulgação",
    icone: "🔒", cor: "#67e8f9", status: "ativo", versao: 1,
    tituloDocumento: "Acordo de Confidencialidade",
    preambulo: "As partes acima qualificadas celebram o presente ACORDO DE CONFIDENCIALIDADE (NDA), mediante as cláusulas seguintes.",
    fechamento: "E, por estarem justas e acordadas, firmam o presente em 2 (duas) vias de igual teor.",
    campos: [
      { id: "c-prazo", label: "Prazo de sigilo", tipo: "texto", variavel: "PRAZO", obrigatorio: true, placeholder: "ex: 5 (cinco) anos" },
      { id: "c-foro", label: "Cidade do foro", tipo: "texto", variavel: "CIDADE_FORO", obrigatorio: true },
    ],
    clausulasObrigatorias: ["cl-confidencialidade", "cl-lgpd", "cl-foro"],
    clausulasOpcionais: ["cl-nao-concorrencia"],
    minAssinantes: 2,
  },
];

export const SEED_REGRAS: Regra[] = [
  {
    id: "rg-garantia-5k",
    nome: "Valor alto → cláusula de garantia",
    campo: "VALOR",
    operador: ">",
    valor: "5000",
    clausulaId: "cl-garantia",
    ativa: true,
  },
  {
    id: "rg-parcelado-inadimplencia",
    nome: "Parcelado → cláusula de inadimplência",
    campo: "FORMA_PAGAMENTO",
    operador: "contem",
    valor: "Parcelado",
    clausulaId: "cl-multa-inadimplencia",
    ativa: true,
  },
  {
    id: "rg-confidencialidade-20k",
    nome: "Valor > 20 mil → confidencialidade",
    campo: "VALOR",
    operador: ">",
    valor: "20000",
    clausulaId: "cl-confidencialidade",
    ativa: true,
  },
  {
    id: "rg-menor-responsavel",
    nome: "Aluno menor → responsável legal",
    campo: "ALUNO_MENOR",
    operador: "=",
    valor: "Sim",
    clausulaId: "cl-responsavel-legal",
    ativa: true,
  },
];
